# Generated by Django 5.2.7 on 2025-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='projects/', verbose_name='Фото проекта')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Наши услуги', 'verbose_name_plural': 'Наши услугии'},
        ),
    ]
