# Generated by Django 5.2.7 on 2025-10-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about_project_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание проекта'),
            preserve_default=False,
        ),
    ]
