# Generated by Django 5.2.7 on 2025-10-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('position', models.CharField(max_length=150, verbose_name='Должность / компания')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
