# Generated by Django 5.2.7 on 2025-10-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contact_contactinfo_design_vacancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=20, verbose_name='Уровень')),
                ('work_type', models.CharField(choices=[('office', 'Полный рабочий день'), ('remote', 'Удаленно'), ('hybrid', 'Гибридный график')], max_length=20, verbose_name='График работы')),
            ],
        ),
    ]
